# Generated by Django 3.1 on 2020-08-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynewsfb',
            name='content',
            field=models.TextField(default='content', max_length=10000),
        ),
        migrations.AddField(
            model_name='mynewsfb',
            name='lead',
            field=models.CharField(default='content', max_length=250),
            preserve_default=False,
        ),
    ]
