# Generated by Django 3.1 on 2020-08-30 20:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200826_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynewsfb',
            name='myurl',
            field=models.URLField(default='myurl', unique=True),
        ),
        migrations.AlterField(
            model_name='mynewsfb',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
