# Generated by Django 3.1 on 2020-08-30 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200830_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynewsfb',
            name='myurl',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
