# Generated by Django 3.1 on 2020-08-31 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200830_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynewsfb',
            name='myurl',
        ),
    ]
