# Generated by Django 3.1 on 2020-09-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_mynewsfb_myurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynewsfb',
            name='time_created_varzesh3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
