# Generated by Django 3.1 on 2020-09-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_mynewsfb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynewsfb',
            name='time_created_varzesh3',
        ),
        migrations.AddField(
            model_name='mynewsfb',
            name='mydate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mynewsfb',
            name='mytime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
