# Generated by Django 3.1 on 2020-09-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200905_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynewsfb',
            options={},
        ),
    ]
